Update build-iso.yml

diff --git a/.github/workflows/build-iso.yml b/.github/workflows/build-iso.yml
--- a/.github/workflows/build-iso.yml
+++ b/.github/workflows/build-iso.yml
@@ -22,11 +22,11 @@ on:
       profile:
         description: '请输入要编译固件大小 单位(MB)'
         required: true
-        default: '1024'
+        default: '2048'
       include_docker:
         description: "是否编译 Docker 插件"
         required: true
-        default: 'yes'
+        default: 'no'
         type: choice
         options:
           - 'yes'
@@ -61,6 +61,15 @@ jobs:
 
       - name: Set executable permissions
         run: chmod +x ${{ github.workspace }}/x86-64/build24.sh
+
+      - name: Validate PPPoE Inputs
+        run: |
+          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
+            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
+              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
+              exit 1
+            fi
+          fi
       
       - name: Enable Store integration
         run: |
@@ -68,16 +77,8 @@ jobs:
             echo 'CUSTOM_PACKAGES="$CUSTOM_PACKAGES luci-app-store"' >> shell/custom-packages.sh
             echo "✅ 已追加 luci-app-store"
           else
-            echo "❎ 未启用 luci-app-store"
-          fi
-
-      - name: Validate PPPoE Inputs
-        run: |
-          if [[ "${{ github.event.inputs.enable_pppoe }}" == "yes" ]]; then
-            if [[ -z "${{ github.event.inputs.pppoe_account }}" || -z "${{ github.event.inputs.pppoe_password }}" ]]; then
-              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
-              exit 1
-            fi
+            echo 'CUSTOM_PACKAGES="$CUSTOM_PACKAGES -luci-app-store -luci-app-quickstart -luci-i18n-quickstart-zh-cn"' >> shell/custom-packages.sh
+            echo "❎ 未启用商店，已排除 store/quickstart 相关包"
           fi
 
       - name: ✅ 正在构建ImmortalWrt固件
@@ -96,6 +97,7 @@ jobs:
               -v "${{ github.workspace }}/x86-64/imm.config:/home/build/immortalwrt/.config" \
               -v "${{ github.workspace }}/shell:/home/build/immortalwrt/shell" \
               -v "${{ github.workspace }}/x86-64/build24.sh:/home/build/immortalwrt/build.sh" \
+              -e ENABLE_STORE=${{ github.event.inputs.enable_store }} \
               -e PROFILE=$profile \
               -e INCLUDE_DOCKER=$include_docker \
               -e ENABLE_PPPOE=${{ inputs.enable_pppoe }} \
